### PR TITLE
Add usefull commands for cleanimg docker ecosystem

### PR DESCRIPTION
**Pull request by ozlevka-work**
Add clean all 
And clean all unused command in Remove section

### CODE REVIEW

**Comment by eon01** [comment]
Hi there, thanks ;-)
I run docker system command and I can't find the clean option.

```
docker system

Usage:	docker system COMMAND

Manage Docker

Options:
      --help   Print usage

Commands:
  df          Show docker disk usage
  events      Get real time events from the server
  info        Display system-wide information
  prune       Remove unused data
```

This is my Docker version:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Is this the same version you're running ? 
Do you have any link to the documentation of ``` docker system clean all ``` ?

**Comment by ozlevka-work** [comment]
You right . I fix the pull request

It's should be docker system prune


Lev Ozeryansky

Senior Software Developer

____________________________________________

________________________________

**Comment by milewski** [comment]
Note that in windows and linux/mac this has a different behavior.... in linux/mac prune will "reclaim" the disk space.. however sadly in windows it only goes up and up... which at a certain point you are forced to manually "resize" the whole docker disk image

**Comment by eon01** [comment]
@ozlevka-ericom thanks but I can't see your code updated with the new commands, I still see the docker system clean command.
@milewski yes, it would be great if we add it as a comment to this git along with the docker prune command

**Comment by ozlevka-work** [comment]
@eon01 I'm sorry for delay.
Right now I commit new correct commands

**Comment by ozlevka-work** [comment]
@milewski What docker version you speaking about?

**Comment by milewski** [comment]
the latest as from today.. but it seens more to be like a bug with docker...  
as pointed out here in this [comment ](https://github.com/moby/moby/issues/21925#issuecomment-323495832)removing container with `-v` before pruning "reclaim" disk space

**Comment by eon01** [comment]
@ozlevka-ericom I merged your PR. Thanks :+1:

**Pull request merged**
